language: node_js
node_js: "11"

os:
- linux
  dist: trusty
- osx
  osx_image: xcode10

cache:
  - npm
  - yarn
  - directories:
    - node_modules
    - $HOME/.cache/electron

addons:
  apt:
    packages:
    - rpm

before_instal
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
- export PATH="$HOME/.yarn/bin:$PATH"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- npm install
- npm update

script:
- electron-forge make .
