language: node_js
node_js: "11"

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - fakeroot
          - rpm
          - xvfb
    - os: osx
      osx_image: xcode10

cache:
  - npm
  - yarn: true
  - directories:
    - node_modules
    - $HOME/.cache/electron


before_install:
- export PATH="$HOME/.yarn/bin:$PATH"
- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

install:
- npm install
- npm update

script:
#- electron-forge make .
- yarn make
